{% set name = "msrestazure" %}
{% set version = "0.6.4.post1" %}
{% set sha256 = "39842007569e8c77885ace5c46e4bf2a9108fcb09b1e6efdf85b6e2c642b55d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - adal >=0.6.0,<2.0.0
    - msrest >=0.6.0,<2.0.0
    - six

test:
  imports:
    - msrestazure
    - msrestazure.azure_active_directory
    - msrestazure.azure_exceptions
    - msrestazure.azure_operation

about:
  home: https://github.com/Azure/msrestazure-for-python
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: The runtime library "msrestazure" for AutoRest generated Python clients

extra:
  recipe-maintainers:
    - dhirschfeld
